---
title: "Async Week 1"
description: "..."
date: 2026-01-18
---

# Leer, eschuchar y pronounciar (to read, to listen and to pronounce)

## Lee y escucha el siguiente texto (read and listen to the following text)

- Lucy is a designer graphic and lives with her girlfriend in a apartment small in Bogotá
- Mondays and Wednesdays she works at home; prepares coffee, reviews emails and starts work at 9:30
- She likes to work in the kitchen because it has much light, but when necesary more concentration use her office.
- At noon she lunches something quickly and takes a walk around the neighborhood with her dog Fiona
- For the afternoon she exercises and watches a movie or a series.
- She really likes the science fiction and terror.
- Tuesdays, Thursdays and Fridays she has to go to the office, that is in the center of the city.
- No it like much to have to travel so much, but she has a good relationship with her coworkers.
- When leaving work, many times they go to drink a beer at the bar of the corner.
- The weekends, often she goes out with her friends or YYY her family.

# Escuchar y hablar

## Escucha este audio y trata de responder esta preguntas (listen to this audio and try to answer these questions)

- How is the person that speaks? Tried but happy
- Where are they? Venecia
- What are they going to do later? Go to drink coffee and walk the city

# Notes

## Pronouns Plurality (examples with "gustar")

- le gusta -> he/she likes (singular pronoun, singular verb)
- le gustan -> he/she likes (singular pronoun, plural verb)
- les gusta -> they like (plural pronoun, singular verb)
- les gustan -> they like (plural pronoun, plural verb)

## Misc

- esperando a: waiting for
- le gusta -> he/she likes
- que está -> that is
- que ir a -> to go to
- sale con: he/she goes out with
- salen: they go out
- sus <noun> -> his/her/its/your (formal) <noun>
- tener que -> to have to
- tiene que ir a -> has to go to
- usa su <noun> -> use his/her <noun>
- van a venir: they are going to come
- van a: they are going to
- ve a: he/she goes to
- venir: to come
